resolver: lts-15.1 # 8.8.2  - base-4.13
# resolver: lts-14.27  # 8.6.5  - base-4.12
# resolver: lts-12.26  # 8.4.4  - base-4.11
# resolver: lts-11.22  # 8.2.2  - base-4.10
# resolver: lts-9.21   # 8.0.2  - base-4.9
# resolver: lts-6.35   # 7.10.3 - base-4.8

extra-deps:
  # - direct-sqlcipher-2.3.26
  # - ../direct-sqlcipher
  - github: simplex-chat/direct-sqlcipher
    commit: 477955063df65a2776c2a958b656ff359b76374d
